#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ClassTimeTable.Resource", IsApplication=true)]

namespace ClassTimeTable
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int AddFragmentToolbar = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int dayEditText = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int editText1 = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int locationEditText = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int menu_Add = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int menu_Delete = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int menu_Edit = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int menu_monday = 2131099662;
			
			// aapt resource value: 0x7f060000
			public const int relativeLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int relativeLayout2 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int relativeLayout3 = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int textView1 = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int timeEditText = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int toolbar = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int week_toolbar = 2131099658;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int AddFragment = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Main = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ToolBar = 2130837506;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int top_menu = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int week_menus = 2131034113;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int MyTheme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
